services:
  backend:
    build:
      context: ./
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:root@db:5432/mydb

    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:17
    ports:
      - 5432:5432
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb

    volumes:
      - postgres_data:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # postgres:
  #   image: postgres:14-alpine
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ~/apps/postgres:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=S3cret
  #     - POSTGRES_USER=citizix_user
  #     - POSTGRES_DB=xyz_db

volumes:
  postgres_data:
